// <auto-generated />
using System;
using Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectAyallaEfratNoa;

#nullable disable

namespace projectAyallaEfratNoa.Migrations
{
    [DbContext(typeof(WorkContext))]
    partial class WorkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Hebrew_100_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectAyallaEfratNoa.Business", b =>
                {
                    b.Property<string>("BusinessCity")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("businessCity");

                    b.Property<string>("BusinessId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("businessId");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("businessName");

                    b.Property<string>("LanguageId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("languageId");

                    b.Property<double?>("NumWeekHours")
                        .HasColumnType("float")
                        .HasColumnName("numWeekHours");

                    b.Property<bool?>("ProfessionType")
                        .HasColumnType("bit")
                        .HasColumnName("professionType");

                    b.Property<double?>("SalaryHour")
                        .HasColumnType("float")
                        .HasColumnName("salaryHour");

                    b.Property<int?>("SeniorityBusiness")
                        .HasColumnType("int")
                        .HasColumnName("seniorityBusiness");

                    b.ToTable("Business", (string)null);
                });

            modelBuilder.Entity("projectAyallaEfratNoa.Language1", b =>
                {
                    b.Property<string>("Discription")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("discription");

                    b.Property<string>("LanguageId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("languageId");

                    b.ToTable("language1", (string)null);
                });

            modelBuilder.Entity("projectAyallaEfratNoa.User1", b =>
                {
                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<double?>("ExpectationsSalary")
                        .HasColumnType("float")
                        .HasColumnName("expectationsSalary");

                    b.Property<string>("Mail")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mail");

                    b.Property<string>("Name1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name1");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone");

                    b.Property<bool?>("ProfessionType")
                        .HasColumnType("bit")
                        .HasColumnName("professionType");

                    b.Property<string>("UserCity")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("userCity");

                    b.Property<string>("UserId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("userId");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("userName");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("userPassword");

                    b.Property<double?>("UserSeniority")
                        .HasColumnType("float")
                        .HasColumnName("userSeniority");

                    b.ToTable("User1", (string)null);
                });

            modelBuilder.Entity("projectAyallaEfratNoa.UserProperty", b =>
                {
                    b.Property<string>("Diploma")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("diploma");

                    b.Property<string>("LanguageId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("languageId");

                    b.Property<double?>("NumMonthLearn")
                        .HasColumnType("float")
                        .HasColumnName("numMonthLearn");

                    b.Property<int?>("SeniorityLanguage")
                        .HasColumnType("int")
                        .HasColumnName("seniorityLanguage");

                    b.Property<string>("UserId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("userId");

                    b.Property<string>("UserPropertiesId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable("UserProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
